### ISSUE TITLE
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'

### ISSUE THREAD

**Issue by zomars** [Maxvien/next-shopify-storefront#35]
On a freshly cloned copy, I've ran `npm install` then  `npm run dev` and I'm getting this error:

```
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at OMMITED/next-shopify-storefront/node_modules/apollo-boost/lib/bundle.cjs.js:127:74
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (OMMITED/next-shopify-storefront/node_modules/apollo-boost/lib/bundle.cjs.js:127:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.apollo-boost (OMMITED/next-shopify-storefront/.next/server/static/development/pages/webpack:/external "apollo-boost":1:1)
    at __webpack_require__ (OMMITED/next-shopify-storefront/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Module../services/checkout.service.ts (OMMITED/next-shopify-storefront/.next/server/static/development/pages/_app.js:2455:70)
    at __webpack_require__ (OMMITED/next-shopify-storefront/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Module../services/index.ts (OMMITED/next-shopify-storefront/.next/server/static/development/pages/webpack:/services/index.ts:1:1)
    at __webpack_require__ (OMMITED/next-shopify-storefront/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
```

**Comment by maithanhnhan** [comment]
This sounds a lot like [#4843](https://github.com/apollographql/apollo-client/issues/4843). Try upgrading apollo-boost to 0.4.1 and see if that fixes it

**Comment by zomars** [comment]
Thanks for the advice @maithanhnhan 🙏 . I've ran `yarn upgrade-interactive --latest` and upgraded all dependencies to their latest version. Also made some required upgrades, since latest next js version has TypeScript support. All good so far, but now I'm getting syntax errors:

```

[ error ] ./pages/_app.tsx
SyntaxError: /Users/zomars/Sites/next-shopify-storefront/pages/_app.tsx: Unexpected token (8:9)

   6 |
   7 | class MyApp extends App {
>  8 |   public static async getInitialProps({ Component, ctx }) {
     |          ^
   9 |     const { req, res, store } = ctx;
  10 |     const pageProps = Component.getInitialProps ? await Component.getInitialProps(ctx) : {};
  11 |
```

**Comment by zomars** [comment]
Nevermind. I've reverted all my changes and just upgraded apollo-boost and it's working now. I'll make a PR with this change. Thanks!

**Comment by Maxvien** [comment]
Thank you @zomars! I have just merged your PR.
