### ISSUE TITLE
internal/modules/cjs/loader.js:985  throw err;

### ISSUE THREAD

**Issue by TechStacker** [Maxvien/next-shopify-storefront#41]
Thank you for putting this great demo out there! Unfortunately, I can't run it locally, I get this error: 

````
> next-shopify-storefront@2.0.0 start /Users/david/Dev/next-shopify-storefront
> NODE_ENV=production node dist/index.js

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/Users/david/Dev/next-shopify-storefront/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-shopify-storefront@2.0.0 start: `NODE_ENV=production node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the next-shopify-storefront@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2020-04-19T11_29_46_239Z-debug.log
David:next-shopify-storefront david$ 

````

Using Node v12.16.1 & Npm v6.13.4 if that's relevant. 

Any ideas? :)

**Comment by VienDinhCom** [comment]
Hi @TechStacker 

I released version v2 here: https://github.com/maxvien/next-shopify-storefront/tree/v2

I hope it could solve your problems.
